# Generated by Django 3.0.1 on 2019-12-29 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todohistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AddField(
            model_name='todoitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
